### Fetch all tasks

GET http://localhost:3200/tasks
Content-Type: application/json

POST http://localhost:3200/tasks
Content-Type: application/json
{
    "title": "Lorem ipsum123",
    "date":"2025-03001T12:00:00Z",
    "description":"Lorem ipsum",
    "priority":"normal",
    "status":"todo"
}

PUT http://localhost:3200/tasks
Content-Type: application/json
{
    "id": "1afc8f07-53ba-4085-b479-3ba8252ba783",
    "status":"inProgress"
}